; ==============================
; Assembly Code Generated By CuteASM
; Time: 2025-08-02 02:34:46
; Architecture: x86
; OS: linux
; ==============================

; ==============================
; Function:test.hiMyLang2
test.hiMyLang2:
    if_1:
    end_if_1:
    if_2:
    else_if_2:
    end_if_2:

; Function End:test.hiMyLang2
; ==============================

; ==============================
; Function:test.hiFn2
test.hiFn2:
    if_3:
    else_if_3:
    end_if_3:
    if_4:
    else_if_4:
    end_if_4:
    if_5:
    end_if_5:

; Function End:test.hiFn2
; ==============================

; ==============================
; Function:test.print0
test.print0:

; Function End:test.print0
; ==============================

; ==============================
; Function:test.main0
test.main0:

; Function End:test.main0
; ==============================

; ==============================
; Function:main
main:

; Function End:main
; ==============================

